"""Initial migration

Revision ID: 840dcdbbd161
Revises: 
Create Date: 2025-05-22 01:27:32.250535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840dcdbbd161'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('impact', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='news_impact'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='News title'),
    sa.Column('content', sa.Text(), nullable=False, comment='News content'),
    sa.Column('source', sa.String(length=100), nullable=True, comment='News source'),
    sa.Column('published_at', sa.DateTime(), nullable=False, comment='Published at'),
    sa.Column('fetched_at', sa.DateTime(), nullable=False, comment='Fetched at'),
    sa.Column('sentiment_score', sa.Float(), nullable=True, comment='Sentiment score [-1,1]'),
    sa.Column('processed', sa.Boolean(), nullable=False, comment='Processed by RAG'),
    sa.Column('url', sa.String(length=512), nullable=True, comment='News URL'),
    sa.Column('affected_assets', sa.JSON(), nullable=True, comment='Affected assets (array)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_articles_processed', 'news_articles', ['processed'], unique=False)
    op.create_index('ix_news_articles_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_index('ix_news_articles_sentiment_score', 'news_articles', ['sentiment_score'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.String(length=50), nullable=False, comment='Telegram user ID'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='Telegram username'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='User email'),
    sa.Column('whitelist_status', sa.Boolean(), nullable=False, comment='Whitelist access'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Created at'),
    sa.Column('last_active', sa.DateTime(), nullable=True, comment='Last active time'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='User settings (JSON)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_index('ix_users_whitelist_status', 'users', ['whitelist_status'], unique=False)
    op.create_table('xai_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False, comment='XAI explanation text'),
    sa.Column('factors_used', sa.JSON(), nullable=True, comment='Factors used for explanation (JSON)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Created at'),
    sa.Column('model_version', sa.String(length=50), nullable=True, comment='XAI model version'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_xai_explanations_created_at', 'xai_explanations', ['created_at'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('direction', sa.Enum('BUY', 'SELL', name='signal_direction'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_executed', sa.Boolean(), nullable=True),
    sa.Column('asset_pair', sa.String(length=20), nullable=False, comment='Asset pair (e.g., BTC/USDT)'),
    sa.Column('signal_type', sa.String(length=10), nullable=False, comment='Signal type (BUY/SELL/HOLD)'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='Confidence score [0,1]'),
    sa.Column('price_at_signal', sa.Float(), nullable=False, comment='Price at signal time'),
    sa.Column('target_price', sa.Float(), nullable=True, comment='Target price'),
    sa.Column('stop_loss', sa.Float(), nullable=True, comment='Stop loss level'),
    sa.Column('time_frame', sa.String(length=10), nullable=False, comment='Time frame'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Signal expiration time'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Signal status'),
    sa.Column('technical_indicators', sa.JSON(), nullable=True, comment='Technical indicators (JSON)'),
    sa.Column('xai_explanation_id', sa.Integer(), nullable=True),
    sa.Column('smart_money_influence', sa.Float(), nullable=True, comment='Smart money influence [-1,1]'),
    sa.Column('volatility_estimate', sa.Float(), nullable=True, comment='Volatility estimate'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='ck_signals_confidence_score'),
    sa.CheckConstraint('smart_money_influence >= -1 AND smart_money_influence <= 1', name='ck_signals_smart_money_influence'),
    sa.ForeignKeyConstraint(['xai_explanation_id'], ['xai_explanations.id'], name='fk_signals_xai_explanation_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_asset_pair', 'signals', ['asset_pair'], unique=False)
    op.create_index('ix_signals_created_at', 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index('ix_signals_signal_type', 'signals', ['signal_type'], unique=False)
    op.create_index('ix_signals_status', 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('signal_news_relevance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False, comment='Relevance score [0,1]'),
    sa.Column('impact_type', sa.String(length=20), nullable=False, comment='Impact type (POSITIVE/NEGATIVE/NEUTRAL)'),
    sa.ForeignKeyConstraint(['news_id'], ['news_articles.id'], name='fk_signal_news_relevance_news_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name='fk_signal_news_relevance_signal_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_news_relevance_news_id', 'signal_news_relevance', ['news_id'], unique=False)
    op.create_index('ix_signal_news_relevance_relevance_score', 'signal_news_relevance', ['relevance_score'], unique=False)
    op.create_index('ix_signal_news_relevance_signal_id', 'signal_news_relevance', ['signal_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='trade_side'), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='trade_status'), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False, comment='Trade volume'),
    sa.Column('pnl_percentage', sa.Float(), nullable=True, comment='PnL percentage'),
    sa.Column('entry_time', sa.DateTime(), nullable=False, comment='Entry time'),
    sa.Column('exit_time', sa.DateTime(), nullable=True, comment='Exit time'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Trade notes'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name='fk_trades_signal_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_trades_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_signal_news_relevance_signal_id', table_name='signal_news_relevance')
    op.drop_index('ix_signal_news_relevance_relevance_score', table_name='signal_news_relevance')
    op.drop_index('ix_signal_news_relevance_news_id', table_name='signal_news_relevance')
    op.drop_table('signal_news_relevance')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index('ix_signals_status', table_name='signals')
    op.drop_index('ix_signals_signal_type', table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index('ix_signals_created_at', table_name='signals')
    op.drop_index('ix_signals_asset_pair', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_xai_explanations_created_at', table_name='xai_explanations')
    op.drop_table('xai_explanations')
    op.drop_index('ix_users_whitelist_status', table_name='users')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_news_articles_sentiment_score', table_name='news_articles')
    op.drop_index('ix_news_articles_published_at', table_name='news_articles')
    op.drop_index('ix_news_articles_processed', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
